################################################################################
#
# Library makefile
#
# Needs following variables
#
# FC  Fortran compiler
# FCFLAGS  Fortran compiler flags
# LN  Linker
# LNFLAGS  Linker flags
#
################################################################################
.SUFFIX:
.SUFFIX: .f90 .o

.PHONY: lib clean distclean

LIBD3 = libdftd3.a

TEST_LIBD3 = test_libdftd3

D3OBJS= libdftd3.o dftd3.o copyc6.o param.o pars.o common.o

OBJS = test_libdftd3.o

all: $(LIBD3) $(TEST_LIBD3)

$(LIBD3): $(D3OBJS)
	ar r $@ $^

$(TEST_LIBD3): $(LIBD3) $(OBJS)
	$(LN) -o $@ $(LNFLAGS) $^

clean:
	rm -f *.o

distclean: clean
	rm -f *.mod $(LIBD3) $(TEST_LIBD3)


%.o: %.f90
	$(FC) $(FCFLAGS) -c $< -o $@


# Dependencies
test_libdftd3.o: $(LIBD3)
libdftd3.o: dftd3.o copyc6.o param.o
dftd3.o: common.o param.o
copyc6.o: param.o pars.o common.o
param.o:
pars.o:
